### ISSUE TITLE
Exception when using token-based authentication in ASP.NET app hosted in IIS

### ISSUE THREAD

**Issue by alexalok** [alexalok/dotAPNS#16]
The cause is explained at https://stackoverflow.com/a/1345402

```
System.TypeInitializationException: The type initializer for 'RestService.RestServiceImpl' threw an exception. ---> System.Security.Cryptography.CryptographicException: The system cannot find the file specified.

   at System.Security.Cryptography.NCryptNative.ImportKey(SafeNCryptProviderHandle provider, byte[] keyBlob, string format)
   at System.Security.Cryptography.CngKey.Import(byte[] keyBlob, string curveName, CngKeyBlobFormat format, CngProvider provider)
   at System.Security.Cryptography.CngKey.Import(byte[] keyBlob, CngKeyBlobFormat format, CngProvider provider)
   at dotAPNS.ApnsClient.CreateUsingJwt(HttpClient http, ApnsJwtOptions options)
   at [REDACTED].Common.Extensions.DotApnsExtensions+<>c.<.cctor>b__2_0() in C:\[REDACTED]\[REDACTED]\Common\Extensions\DotApnsExtensions.cs:line 11
   at System.Lazy<T>.CreateValue()
   at System.Lazy<T>.LazyInitValue()
   at System.Lazy<T>.get_Value()
   at [REDACTED].Common.Extensions.DotApnsExtensions.GetApnsClient() in C:\[REDACTED]\[REDACTED]\Common\Extensions\DotApnsExtensions.cs:line 21
   at RestService.RestServiceImpl..cctor() in C:\[REDACTED]\[REDACTED]\RestService\RestServiceImpl.svc.cs:line 45   --- End of inner exception stack trace ---
   at RestService.RestServiceImpl..ctor() in C:\[REDACTED]\[REDACTED]\RestService\RestServiceImpl.svc.cs:line 40
   at CreateRestService.RestServiceImpl()
   at System.ServiceModel.Dispatcher.InstanceProvider.GetInstance(InstanceContext instanceContext, Message message)
   at System.ServiceModel.Dispatcher.InstanceBehavior.GetInstance(InstanceContext instanceContext, Message request)
   at System.ServiceModel.InstanceContext.GetServiceInstance(Message message)
   at System.ServiceModel.Dispatcher.InstanceBehavior.EnsureServiceInstance(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(bool isOperationContextSet)
```

**Comment by alexalok** [comment]
Seems to be fixed either on CLR or IIS side, at least on the latest versions. Should anyone bump into a similar issue, there's a quick and simple workaround explained [here](https://stackoverflow.com/a/10048789).
