### ISSUE TITLE
The message received was unexpected or badly formatted. 

### ISSUE THREAD

**Issue by sachinp-cm** [alexalok/dotAPNS#49]
Hi I am using .NET Core 3.1 for writing AWS Lambda and using the Certificate based option to send push notification to APNS however I am getting the error - The message received was unexpected or badly formatted. 

this is the code, I am using:

 private async Task<ApnsResponse> SendAsync(
             byte[] certificate,
             string certPassword,
             string message,
             string destination)
        {
            var x509 = new X509Certificate2(certificate, certPassword);
            var applePushNotificationService = ApnsClient.CreateUsingCert(x509);
            var push = new ApplePush(ApplePushType.Alert)
            .AddAlert(message)
            .AddToken(destination);
            return await applePushNotificationService.SendAsync(push);
        }

**Comment by alexalok** [comment]
This is *probably* caused by the underlying infrastructure not supporting HTTP/2 connections. Unfortunately without more verbose error description it's hard for me to come up with the possible solution. A full stacktrace might be helpful.

**Comment by sachinp-cm** [comment]
at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsyncCore>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<GetHttp2ConnectionAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__70.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at dotAPNS.ApnsClient.<SendAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wtp.AWS.API.Stack.Services.APNSService.<SendAsync>d__1.MoveNext() in \Services\APNSService.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wtp.AWS.API.Stack.Services.APNSService.<SendAPNSStandardNotificationAsync>d__0.MoveNext() in \Services\APNSService.cs:line 21
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wtp.AWS.API.Stack.Lambda.Functions.StandardNotificationToAPNSFunction.<HandleSQSEvent>d__4.MoveNext() in \Functions\StandardNotificationToAPNSFunction.cs:line 39

**Comment by sachinp-cm** [comment]
I am running it using unit test from within Visual Studio Enterprise 2019 edition. What do you mean by "underlying infrastructure not supporting HTTP/2 connections.", how can I check or ensure it?

**Comment by sachinp-cm** [comment]
![image](https://user-images.githubusercontent.com/74224726/99526098-e53f0580-29ee-11eb-8631-91cd4dfe4ca8.png)

**Comment by alexalok** [comment]
Could you try running a simple example in the console application without AWS Lambda? There were a few reports on dotAPNS not working due to lack of proper HTTP/2 support on older Windows versions. Are you running on Windows 10/Windows Server 2019?

**Comment by sachinp-cm** [comment]
I am using 
![image](https://user-images.githubusercontent.com/74224726/99588657-0a5b6480-2a3f-11eb-8f20-2d01ec660f78.png)

**Comment by sachinp-cm** [comment]
Same issue with Console application 
![image](https://user-images.githubusercontent.com/74224726/99589375-00863100-2a40-11eb-9fc6-12b43f57ba25.png)

**Comment by alexalok** [comment]
Might be related to [this](https://stackoverflow.com/a/38853601/10307803). Perhaps you could try running on another machine? Sadly, the error still seems quite bogus to me.

**Comment by sachinp-cm** [comment]
Used PushSharp and it worked fine. Thanks for looking into this, I am closing the issue as unresolved from my side.

**Comment by alexalok** [comment]
Sorry for not being able to help with this one. Glad that PushSharp worked. Keep in mind however that it uses legacy APNs protocol which will be shut down on 31st of March [according to Apple](https://developer.apple.com/news/?id=c88acm2b).

**Comment by sachinp-cm** [comment]
Do you have an alternative as I am still getting the same error with another machine.

**Comment by alexalok** [comment]
Is it possible for you to email me the certificate you're using? I will have it deleted after the issue is successfully reproduced on my machine.

Another clue might be the firewall or other network settings.

**Comment by alexalok** [comment]
The issue seems stale so I'll go ahead and close it. Please feel free to reopen should you have any more questions!
