### ISSUE TITLE
Error when used in a VB.Net project

### ISSUE THREAD

**Issue by mubaraknet** [alexalok/dotAPNS#71]
I'm getting the below error when I used dotAPNS in a VB.Net project. I have System.Net.Http 4.3.4 and System.Diagnostics.DiagnosticSource also installed

System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at dotAPNS.ApnsClient.<SendAsync>d__17.MoveNext()

**Comment by alexalok** [comment]
Try to explicitly add the latest versions of [System.Net.Http](https://www.nuget.org/packages/System.Net.Http/) and [System.Diagnostics.DiagnosticSource](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/5.0.1) via the NuGet manager.
